### ISSUE TITLE
rake aborted! when activesupport-3.0.20 fails to load jammit

### ISSUE THREAD

**Issue by ganar** [documentcloud/jammit#270]
I'm trying to migrate an old  [teambox 3](https://github.com/teambox/teambox) installation to a new machine and am currently stumped by this error

Upon 

`bundle exec rake --trace db:migrate RAILS_ENV=production`

I get 

```
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
syck has been removed, psych is used instead
rake aborted!
LoadError: cannot load such file -- lib/jammit_loading
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:227:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/mnt/case/home/teambox/tb_3ph/config/initializers/jammit.rb:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `block in load'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:227:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:236:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/engine.rb:201:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/engine.rb:200:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/engine.rb:200:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/initializable.rb:25:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/initializable.rb:25:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/initializable.rb:50:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/initializable.rb:49:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/initializable.rb:49:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/application.rb:134:in `initialize!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/application.rb:77:in `method_missing'
/mnt/case/home/teambox/tb_3ph/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `block in load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:597:in `new_constants_in'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/application.rb:103:in `require_environment!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.0.20/lib/rails/application.rb:218:in `block in initialize_tasks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)

```

this is the file that fails to load > [lib/jammit_loading](https://github.com/teambox/teambox/blob/dev/lib/jammit_loading.rb)

I'm running `ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]`, with gems 

```
*** LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.20, 3.0.9)
actionpack (3.0.20, 3.0.9)
activemodel (4.2.4, 3.0.20, 3.0.9)
activerecord (4.2.4, 3.0.20, 3.0.9)
activeresource (3.0.20, 3.0.9)
activesupport (4.2.4, 3.0.20, 3.0.9)
addressable (2.3.8, 2.2.6)
arel (6.0.3, 2.0.10)
aws-s3 (0.6.2)
aws-sdk (2.1.28)
aws-sdk-core (2.1.28)
aws-sdk-resources (2.1.28)
bigdecimal (1.2.4)
builder (3.2.2, 2.1.2)
bundler (1.7.6)
bundler-unload (1.0.2)
cancan (1.4.1)
capybara (0.4.1.2)
celerity (0.8.9)
cgi_multipart_eof_fix (2.5.0)
childprocess (0.2.2)
chronic (0.5.0)
cocaine (0.1.0)
columnize (0.3.4)
configuration (1.3.1)
cssmin (1.0.3)
cucumber (1.0.2)
cucumber-rails (0.3.2)
culerity (0.2.15)
daemons (1.2.3, 1.1.4)
database_cleaner (0.5.2)
diff-lcs (1.1.2)
dm-active_model (1.2.1)
dm-core (1.2.1)
dm-rails (1.2.1)
erubis (2.6.6)
eventmachine (0.12.10)
executable-hooks (1.3.2)
factory_girl (1.3.3)
faker (0.9.5)
faraday (0.6.1)
fastthread (1.0.7)
ffi (1.0.9)
foreman (0.19.0)
fuubar (0.0.5)
gem-wrappers (1.2.7)
gem_plugin (0.2.3)
gherkin (2.4.5)
haml (3.1.2)
haml-rails (0.3.4)
hashie (1.0.0)
headless (0.2.2)
hpricot (0.8.4)
i18n (0.7.0, 0.5.4, 0.5.0)
icalendar (1.1.6)
iconv (1.0.4)
immortal (0.1.7)
innertube (1.1.0, 1.0.2)
io-console (0.4.2)
jammit (0.6.6, 0.6.3)
jmespath (1.1.3)
joiner (0.3.4)
jsmin (1.0.1)
json (1.8.3, 1.8.1, 1.5.3)
json_pure (1.6.1)
kgio (2.6.0)
launchy (0.3.7)
libxml-ruby (2.4.0)
mail (2.2.20, 2.2.19)
memcache-client (1.8.5)
middleware (0.1.0)
mime-types (1.25.1, 1.16)
minitest (5.8.1, 4.7.5)
multi_json (0.0.5)
multipart-post (1.1.2)
mysql (2.8.1)
nokogiri (1.4.7)
oa-core (0.2.3)
oa-oauth (0.2.3)
oauth (0.4.5)
oauth2 (0.3.0)
open4 (1.1.0)
paperclip (2.3.15)
pg (0.9.0)
pickle (0.4.8)
Platform (0.4.0)
polyglot (0.3.5, 0.3.1)
POpen4 (0.1.4)
psych (2.0.5)
rack (1.2.8, 1.2.3)
rack-mount (0.6.14)
rack-ssl-enforcer (0.2.2)
rack-test (0.5.7)
rails (3.0.20, 3.0.9)
railties (3.0.20, 3.0.9)
raindrops (0.7.0)
rake (10.4.2, 10.1.0, 0.9.2)
rbx-require-relative (0.0.9)
rdiscount (1.6.8)
rdoc (4.1.0, 3.12.2, 3.8)
riddle (1.5.12, 1.3.3)
rspec (2.3.0)
rspec-core (2.3.1)
rspec-expectations (2.3.0)
rspec-instafail (0.1.8)
rspec-mocks (2.3.0)
rspec-rails (2.3.1)
ruby-progressbar (0.0.10)
rubygems-bundler (1.4.4)
rubyzip (0.9.4)
rvm (1.11.3.9)
sass (3.1.4)
selenium-webdriver (2.6.0)
sphinx (2.1.1.3712)
sprockets (1.0.2)
sprockets-rails (0.0.1)
sqlite3-ruby (1.2.5)
teambox-permalink_fu (1.0.2)
term-ansicolor (1.0.5)
test-unit (2.1.5.0)
text-format-revised (1.1.0)
text-hyphen (1.2)
thin (1.2.11)
thinking-sphinx (3.1.4, 2.1.0, 2.0.1)
thor (0.14.6)
thread_safe (0.3.5)
tilt (1.3.3)
timecop (0.3.5)
tmail (1.2.7.1)
treetop (1.4.15, 1.4.9)
tzinfo (1.2.2, 0.3.45, 0.3.29)
unicorn (4.0.1)
webrat (0.7.3)
whenever (0.4.2)
xml-simple (1.1.0)
xpath (0.1.4)
yui-compressor (0.9.6)
```

Any help in this issue is deeply appreciated

**Comment by reefdog** [comment]
Gemfile was specifying the HTTP domain. Fixed; thanks @ganar! You'll have to point your Gemfile to this repo to get this fix until we release.

**Comment by Denswami** [comment]
Hi Kinly re-open this issue, still not working with rails 3.0.5, same issue
